-- SQLite

-- Tabela Employees (Funcionários)

CREATE TABLE EMPLOYEES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(100) NOT NULL,
    LASTNAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    OCCUPATION VARCHAR(133),
    STREET_ADDRES TEXT NOT NULL,
    CITY VARCHAR(150) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIP INTEGER NOT NULL
);